NAME = philo
CC = gcc
CFLAGS = -Wall -Wextra -Werror -pthread

SRCDIR = src
INCDIR = includes
OBJDIR = obj

SOURCES = main.c parsing.c utils.c init.c cleanup.c philosopher.c forks.c sim.c monitor.c
SRCS = $(addprefix $(SRCDIR)/, $(SOURCES))
OBJS = $(addprefix $(OBJDIR)/, $(SOURCES:.c=.o))

all: $(NAME)

$(NAME): $(OBJS)
	$(CC) $(CFLAGS) $(OBJS) -o $(NAME)

$(OBJDIR)/%.o: $(SRCDIR)/%.c
	@mkdir -p $(OBJDIR)
	$(CC) $(CFLAGS) -I$(INCDIR) -c $< -o $@

clean:
	rm -rf $(OBJDIR)

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re
